name: foolbox-evaluation
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  - captum
  - foolbox
  - matplotlib
  - pytorch
  - torchvision
  - pip:
    - lime
    - torchray
